spring.application.name=inventory-api

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/DBNAME?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=DBUsername
spring.datasource.password=DBPassword

# JWT Settings
jwt.secret=DEFINE_A_SECRET_KEY
jwt.expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true